title: Álgebra y Geometría — CS
description: Curso interactivo de Álgebra y Geometría aplicada a Ciencia de la Computación
baseurl: "/Algebra-y-Geometria"
url: "https://ecuadros.github.io"
theme: null
markdown: kramdown
